// services/mockData.ts
// Seed data covering all the role types requested.
// Replace with real MongoDB Atlas fetches once backend is live.

import { Job } from "../types";

export const MOCK_JOBS: Job[] = [
  // ── AI / Prompt Engineering ──────────────────────────────────────
  {
    _id: "1",
    title: "AI / Prompt Engineer Trainee",
    company: "Gaditek",
    location: "Karachi",
    area: "Shahrah-e-Faisal",
    salaryMin: 35,
    salaryMax: 60,
    jobType: "Full-time",
    category: "AI/ML",
    isInternship: false,
    isTrainee: true,
    description:
      "Join our AI team and learn to craft, evaluate and optimize prompts for LLM-powered products.",
    requirements: [
      "Basic Python",
      "Curiosity about LLMs",
      "Strong written English",
    ],
    responsibilities: [
      "Design and iterate on prompts",
      "Evaluate model outputs",
      "Document prompt patterns",
    ],
    tags: ["AI", "Prompt Engineering", "Python", "LLMs"],
    experience: "Fresh / 0–1 Years",
    postedAt: new Date(Date.now() - 2 * 3600000).toISOString(),
    isNew: true,
  },
  {
    _id: "2",
    title: "AI/ML Engineer",
    company: "Systems Ltd",
    location: "Karachi",
    area: "DHA Phase 6",
    salaryMin: 150,
    salaryMax: 280,
    jobType: "Full-time",
    category: "AI/ML",
    isInternship: false,
    isTrainee: false,
    description:
      "Build and deploy production ML pipelines for enterprise clients.",
    requirements: ["3+ years ML", "PyTorch/TensorFlow", "MLOps experience"],
    responsibilities: [
      "Train and fine-tune models",
      "Build inference APIs",
      "Monitor model drift",
    ],
    tags: ["Python", "PyTorch", "MLOps", "AWS"],
    experience: "3+ Years",
    postedAt: new Date(Date.now() - 5 * 3600000).toISOString(),
  },

  // ── Software QA ───────────────────────────────────────────────────
  {
    _id: "3",
    title: "Software QA (Quality Assurance) Intern",
    company: "TPS Worldwide",
    location: "Karachi",
    area: "I.I. Chundrigar Road",
    salaryMin: 20,
    salaryMax: 35,
    jobType: "Internship",
    category: "Software",
    isInternship: true,
    isTrainee: false,
    description:
      "3-month paid internship learning manual and automated testing on fintech products.",
    requirements: ["CS student or fresh grad", "Basic programming"],
    responsibilities: [
      "Write test cases",
      "Report bugs in Jira",
      "Learn Selenium/Cypress",
    ],
    tags: ["QA", "Manual Testing", "Selenium", "Jira"],
    experience: "Fresh",
    postedAt: new Date(Date.now() - 24 * 3600000).toISOString(),
    isNew: true,
  },
  {
    _id: "4",
    title: "QA Intern",
    company: "Arpatech",
    location: "Karachi",
    area: "Korangi Creek",
    salaryMin: 18,
    salaryMax: 30,
    jobType: "Remote",
    category: "Software",
    isInternship: true,
    isTrainee: false,
    description:
      "Remote QA internship for a SaaS product team. Flexible hours.",
    requirements: ["Attention to detail", "Can work remotely"],
    responsibilities: [
      "Regression testing",
      "Bug documentation",
      "Sprint participation",
    ],
    tags: ["QA", "Remote", "Agile"],
    experience: "Fresh",
    postedAt: new Date(Date.now() - 48 * 3600000).toISOString(),
  },

  // ── UI/UX Design ──────────────────────────────────────────────────
  {
    _id: "5",
    title: "UI/UX Design & Research Intern",
    company: "Creative Chaos",
    location: "Karachi",
    area: "Gulshan-e-Iqbal",
    salaryMin: 25,
    salaryMax: 40,
    jobType: "On-site",
    category: "Design",
    isInternship: true,
    isTrainee: false,
    description:
      "Work alongside senior designers on mobile and web products for global clients.",
    requirements: ["Figma proficiency", "Portfolio of student projects"],
    responsibilities: [
      "User research",
      "Wireframing",
      "Usability testing",
      "Design handoff",
    ],
    tags: ["Figma", "UX Research", "Prototyping"],
    experience: "Fresh",
    postedAt: new Date(Date.now() - 3 * 3600000).toISOString(),
    isNew: true,
  },

  // ── Marketing & PR ────────────────────────────────────────────────
  {
    _id: "6",
    title: "Public Relations (PR) & Influencer Relations Intern",
    company: "Daraz",
    location: "Karachi",
    area: "Clifton",
    salaryMin: 22,
    salaryMax: 35,
    jobType: "Hybrid",
    category: "Marketing",
    isInternship: true,
    isTrainee: false,
    description:
      "Support the PR team in managing media relationships and influencer campaigns.",
    requirements: [
      "Excellent communication",
      "Social media savvy",
      "Journalism/Marketing student",
    ],
    responsibilities: [
      "Draft press releases",
      "Manage influencer outreach",
      "Track media coverage",
    ],
    tags: ["PR", "Influencer Marketing", "Social Media"],
    experience: "Fresh",
    postedAt: new Date(Date.now() - 6 * 3600000).toISOString(),
  },
  {
    _id: "7",
    title: "Copywriter & Creative Strategist Intern",
    company: "Symmetry Group",
    location: "Karachi",
    area: "DHA Phase 5",
    salaryMin: 20,
    salaryMax: 35,
    jobType: "Part-time",
    category: "Marketing",
    isInternship: true,
    isTrainee: false,
    description:
      "Part-time creative writing role. Craft compelling copy for digital campaigns.",
    requirements: ["Strong Urdu & English writing", "Creative portfolio"],
    responsibilities: [
      "Write ad copy",
      "Social captions",
      "Email newsletters",
      "Brand stories",
    ],
    tags: ["Copywriting", "Creative Strategy", "Part-time"],
    experience: "Fresh",
    postedAt: new Date(Date.now() - 12 * 3600000).toISOString(),
  },
  {
    _id: "8",
    title: "Growth Marketing / Data Optimization Intern",
    company: "Afiniti",
    location: "Karachi",
    area: "PECHS Block 6",
    salaryMin: 30,
    salaryMax: 50,
    jobType: "Full-time",
    category: "Marketing",
    isInternship: true,
    isTrainee: false,
    description:
      "Analyze funnel data and run A/B tests to optimize digital growth channels.",
    requirements: [
      "Google Analytics",
      "Basic Excel/Sheets",
      "Data-driven mindset",
    ],
    responsibilities: [
      "Funnel analysis",
      "A/B testing",
      "Weekly performance reports",
    ],
    tags: ["Growth Marketing", "Analytics", "Data", "A/B Testing"],
    experience: "Fresh / 0–1 Years",
    postedAt: new Date(Date.now() - 18 * 3600000).toISOString(),
  },

  // ── E-Commerce & Operations ────────────────────────────────────────
  {
    _id: "9",
    title: "E-Commerce, Logistics & Operations Intern",
    company: "Siddiqsons",
    location: "Karachi",
    area: "I.I. Chundrigar Road",
    salaryMin: 20,
    salaryMax: 35,
    jobType: "On-site",
    category: "Operations",
    isInternship: true,
    isTrainee: false,
    description:
      "Learn end-to-end e-commerce operations from order management to last-mile delivery.",
    requirements: ["Supply chain or business student", "MS Excel"],
    responsibilities: [
      "Order processing",
      "Inventory tracking",
      "Vendor coordination",
    ],
    tags: ["E-Commerce", "Logistics", "Operations"],
    experience: "Fresh",
    postedAt: new Date(Date.now() - 30 * 3600000).toISOString(),
  },

  // ── Development ───────────────────────────────────────────────────
  {
    _id: "10",
    title: "MERN Stack / API Development Intern",
    company: "Gaditek",
    location: "Karachi",
    area: "North Nazimabad",
    salaryMin: 30,
    salaryMax: 55,
    jobType: "Remote",
    category: "Software",
    isInternship: true,
    isTrainee: false,
    description:
      "Remote internship building REST APIs and React dashboards for real products.",
    requirements: ["JavaScript basics", "HTML/CSS", "Git"],
    responsibilities: [
      "Build API endpoints",
      "Integrate frontend",
      "Code review participation",
    ],
    tags: ["MERN", "Node.js", "React", "MongoDB", "Remote"],
    experience: "Fresh",
    postedAt: new Date(Date.now() - 4 * 3600000).toISOString(),
    isNew: true,
  },
  {
    _id: "11",
    title: "Flutter / React Native Intern",
    company: "Arpatech",
    location: "Karachi",
    area: "Korangi Creek",
    salaryMin: 25,
    salaryMax: 45,
    jobType: "Hybrid",
    category: "Software",
    isInternship: true,
    isTrainee: false,
    description: "Build cross-platform mobile features under senior guidance.",
    requirements: ["Dart or React Native basics", "Mobile UI understanding"],
    responsibilities: [
      "Implement UI screens",
      "API integration",
      "Play Store / App Store deployment",
    ],
    tags: ["Flutter", "React Native", "Mobile", "Hybrid"],
    experience: "Fresh",
    postedAt: new Date(Date.now() - 36 * 3600000).toISOString(),
  },
  {
    _id: "12",
    title: "Full-Stack Consultant",
    company: "Systems Ltd",
    location: "Karachi",
    area: "DHA Phase 6",
    salaryMin: 200,
    salaryMax: 350,
    jobType: "Full-time",
    category: "Software",
    isInternship: false,
    isTrainee: false,
    description:
      "Consult and build full-stack solutions for enterprise clients across MENA.",
    requirements: [
      "5+ years",
      "React, Node.js, PostgreSQL",
      "Client-facing experience",
    ],
    responsibilities: [
      "Solution architecture",
      "Client workshops",
      "Team leadership",
    ],
    tags: ["Full-Stack", "React", "Node.js", "PostgreSQL", "Consulting"],
    experience: "5+ Years",
    postedAt: new Date(Date.now() - 2 * 24 * 3600000).toISOString(),
  },

  // ── Account Management ────────────────────────────────────────────
  {
    _id: "13",
    title: "Account Management / Client Operations Trainee",
    company: "Habib Bank Limited (HBL)",
    location: "Karachi",
    area: "I.I. Chundrigar Road",
    salaryMin: 45,
    salaryMax: 70,
    jobType: "Full-time",
    category: "Finance",
    isInternship: false,
    isTrainee: true,
    description:
      "Structured trainee program in client account management at Pakistan's largest bank.",
    requirements: ["BBA/MBA", "Strong communication", "MS Office"],
    responsibilities: ["Client onboarding", "Portfolio support", "Reporting"],
    tags: ["Banking", "Account Management", "Finance", "Trainee"],
    experience: "Fresh / 0–1 Years",
    postedAt: new Date(Date.now() - 5 * 24 * 3600000).toISOString(),
  },
  {
    _id: "14",
    title: "Management Trainee Program",
    company: "Daraz",
    location: "Karachi",
    area: "Clifton",
    salaryMin: 60,
    salaryMax: 90,
    jobType: "Full-time",
    category: "Management",
    isInternship: false,
    isTrainee: true,
    description:
      "12-month structured MTP rotating across Operations, Marketing and Tech at Daraz.",
    requirements: ["MBA or top-tier BBA", "Leadership skills", "CGPA 3.5+"],
    responsibilities: [
      "Cross-functional rotations",
      "Project ownership",
      "Executive presentations",
    ],
    tags: ["MTP", "Management", "Rotational", "Leadership"],
    experience: "Fresh",
    postedAt: new Date(Date.now() - 7 * 24 * 3600000).toISOString(),
  },

  // ── Healthcare / Clinical ─────────────────────────────────────────
  {
    _id: "15",
    title: "Clinical Research Associate (CRA) Intern",
    company: "Searle Company",
    location: "Karachi",
    area: "Gulshan-e-Iqbal",
    salaryMin: 25,
    salaryMax: 40,
    jobType: "On-site",
    category: "Clinical Research",
    isInternship: true,
    isTrainee: false,
    description:
      "Assist CRAs in monitoring clinical trials per GCP guidelines.",
    requirements: ["Pharm-D or MBBS student", "GCP awareness"],
    responsibilities: [
      "Site monitoring visits",
      "Data collection",
      "Adverse event reporting",
    ],
    tags: ["Clinical Research", "CRA", "GCP", "Pharma"],
    experience: "Fresh",
    postedAt: new Date(Date.now() - 48 * 3600000).toISOString(),
  },
  {
    _id: "16",
    title: "Industrial Pharmacy Trainee",
    company: "Getz Pharma",
    location: "Karachi",
    area: "Korangi Industrial Area",
    salaryMin: 35,
    salaryMax: 55,
    jobType: "Full-time",
    category: "Pharmacy",
    isInternship: false,
    isTrainee: true,
    description:
      "Rotational trainee across manufacturing, QA and regulatory departments.",
    requirements: ["Pharm-D", "Production lab experience preferred"],
    responsibilities: [
      "Batch manufacturing",
      "Quality testing",
      "Regulatory documentation",
    ],
    tags: ["Pharmacy", "Industrial", "Manufacturing", "QA"],
    experience: "Fresh / 0–1 Years",
    postedAt: new Date(Date.now() - 3 * 24 * 3600000).toISOString(),
  },

  // ── Architecture / Urban Planning ─────────────────────────────────
  {
    _id: "17",
    title: "Architectural Draftsman",
    company: "Habib Rafiq Pvt Ltd",
    location: "Karachi",
    area: "DHA Phase 2",
    salaryMin: 40,
    salaryMax: 70,
    jobType: "On-site",
    category: "Architecture",
    isInternship: false,
    isTrainee: false,
    description:
      "Produce detailed architectural drawings and 3D models for large-scale projects.",
    requirements: [
      "AutoCAD proficiency",
      "Architecture diploma or degree",
      "Revit is a plus",
    ],
    responsibilities: [
      "Technical drawings",
      "BOQ preparation",
      "Site coordination",
    ],
    tags: ["AutoCAD", "Revit", "Architecture", "Drafting"],
    experience: "1–3 Years",
    postedAt: new Date(Date.now() - 24 * 3600000).toISOString(),
  },
  {
    _id: "18",
    title: "Urban Planning Associate",
    company: "Karachi Metropolitan Corporation",
    location: "Karachi",
    area: "Civic Center",
    salaryMin: 50,
    salaryMax: 80,
    jobType: "On-site",
    category: "Urban Planning",
    isInternship: false,
    isTrainee: false,
    description:
      "Contribute to urban development plans and zoning policies for Karachi.",
    requirements: ["Urban Planning degree", "GIS software", "Policy research"],
    responsibilities: [
      "Land use planning",
      "GIS mapping",
      "Public consultation reports",
    ],
    tags: ["Urban Planning", "GIS", "Policy", "Government"],
    experience: "1–3 Years",
    postedAt: new Date(Date.now() - 4 * 24 * 3600000).toISOString(),
  },
];

export const KARACHI_AREAS = [
  "Clifton",
  "DHA",
  "Gulshan",
  "Korangi",
  "PECHS",
  "Saddar",
  "North Nazimabad",
];
export const JOB_CATEGORIES = [
  "Software",
  "AI/ML",
  "Design",
  "Marketing",
  "Finance",
  "Healthcare",
  "Operations",
  "Management",
  "Architecture",
  "Urban Planning",
  "Pharmacy",
  "Clinical Research",
];
